---
- name: Delete StorageGRID Bucket
  hosts: localhost
  gather_facts: no
  collections:
    - netapp.storagegrid

  vars_files:
    - ../../global_vars.yml

  vars_prompt:
    - name: tenant_id
      prompt: "enter tenant id"
      default: "default"
      private: no

    - name: user_name
      prompt: "enter tenant root user name"
      default: "root"
      private: no

    - name: user_pass
      prompt: "enter tenant root user password"
      default: "br@@mspun111"
      private: yes

    - name: bucket_name
      prompt: "enter bucket name to DELETE"
      default: "default"
      private: no

  tasks:
    - name: Login as tenant
      netapp.storagegrid.na_sg_grid_login:
        hostname: "{{ grid_addr }}"
        username: "{{ user_name }}"
        password: "{{ user_pass }}"
        tenant_id: "{{ tenant_id }}"
        validate_certs: false
      register: auth

    - name: Inspect login result
      debug:
        var: auth

    - name: Set tenant token
      ansible.builtin.set_fact:
        tenant_token: "{{ auth.na_sa_token }}" #this data part full token is auth

    - name: Delete S3 Bucket (tenant token)
      netapp.storagegrid.na_sg_org_container:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ tenant_token }}"
        validate_certs: false
        state: absent
        name: "{{ bucket_name }}"

