- name: Create StorageGRID tenant user
  hosts: localhost
  gather_facts: false

  vars_files:
    - global_vars.yml
  vars_prompt:
    - name: tenant_user_name
      prompt: "Tenant username to create"
      default: "user1"
      private: no
#    - name: tenant_user_pass
#      prompt: "Tenant user password"
#      private: yes

  tasks:

  - name: Create tenant local user (debug mode)
    ansible.builtin.uri:
      url: "{{ grid_endpoint }}/api/v3/org/users"
      method: POST
      body_format: json
      body:
        fullName: "{{ tenant_user_name }}"
        uniqueName: "user/{{ tenant_user_name }}"
        password: "br@@mspun111"
      headers:
        Authorization: "Bearer 93ac4c37-4a60-45b7-85bc-2bca59831b86"
        Content-Type: "application/json"
      validate_certs: false
      # Comment out strict status code to see what you get
      # status_code: 201
    register: tenant_user

  - name: Show full result
    ansible.builtin.debug:
      var: tenant_user

