- name: Create StorageGRID tenant user
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: grid_addr
      prompt: "Grid / tenant address"
      default: "192.168.4.230"
      private: no
    - name: tenant_token
      prompt: "Paste tenant bearer token"
      private: yes
    - name: tenant_user_name
      prompt: "Tenant username to create"
      default: "user1"
      private: no
#    - name: tenant_user_pass
#      prompt: "Tenant user password"
#      private: yes

  tasks:
    - name: Create tenant local user
      ansible.builtin.uri:
        url: "https://{{ grid_addr }}/api/v3/org/users"
        method: POST
        body_format: json
        body:
          fullName: "{{ tenant_user_name }}"
          uniqueName: "user/{{ tenant_user_name }}"
#          password: "{{ tenant_user_pass }}"
        headers:
          Authorization: "Bearer {{ tenant_token }}"
          Content-Type: "application/json"
        validate_certs: false
        status_code: 201
      register: tenant_user

    - name: Show result
      ansible.builtin.debug:
        var: tenant_user.json
