---
- name: Fetch TLS cert from 192.168.4.230
  connection: local
  hosts: localhost

  vars_files: global_vars.yml
  tasks:
    - name: Save server certificate to sgrid-admin.pem
      shell: >
        openssl s_client -connect 192.168.4.230:443 -showcerts \
        </dev/null 2>/dev/null
        | sed -n '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > \
        "{{ playbookdir }}/certs/grid_admin.pem"
