# this playbook will list all tenants' data
---
- name: List StorageGRID tenants
  hosts: localhost
  gather_facts: false

  vars:
    admin_node_ip: "192.168.4.230"
    storagegrid_username: "root"
    storagegrid_password: "br@@mspun111"

  tasks:
    - name: Get bearer token from StorageGRID
      uri:
        url: "https://{{ admin_node_ip }}/api/v3/authorize"
        method: POST
        body_format: json
        body:
          username: "{{ storagegrid_username }}"
          password: "{{ storagegrid_password }}"
        status_code: 200
        validate_certs: false
      register: auth

    - name: Debug token response
      debug:
        var: auth.json

    - name: Set bearer token fact
      set_fact:
        bearer_token: "{{ auth.json.data }}"
      when: auth.json.data is defined

    - name: Get list of tenants from StorageGRID
      uri:
        url: "https://{{ admin_node_ip }}/api/v3/grid/accounts"
        method: GET
        headers:
          Authorization: "Bearer {{ bearer_token }}"
          Accept: "application/json"
        validate_certs: false
      register: tenant_response

    - name: list tenants
      debug:
        msg: "id={{ item.id }}, name={{ item.name }}"
      loop: "{{ tenant_response.json.data }}"
