---
- name: Create StorageGRID load balancer endpoint
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.storagegrid

  vars_files:
    - global_vars.yml

  vars_prompt:
    - name: lb_display_name 
      prompt: "display name"
      default: "------"
      private: "no"
    - name: lb_port 
      prompt: "port"
      default: "------"
      private: "no"
    - name: lb_secure
      prompt: "HTTPS"
      default: "false"
      private: "no"
    - name: lb_default_service_type
      prompt: "default service type"
      default: s3
      private: no
 

    # Optional: custom certificate; omit all three to use default certs
    #    lb_server_certificate: |
    #  -----BEGIN CERTIFICATE-----
    #  YOUR-CERT-HERE
    #  -----END CERTIFICATE-----
    #lb_private_key: |
    #  -----BEGIN PRIVATE KEY-----
    #  YOUR-KEY-HERE
    #  -----END PRIVATE KEY-----
    #lb_ca_bundle: ""   # or a PEM bundle

  tasks:

    - name: Get StorageGRID auth token
      netapp.storagegrid.na_sg_grid_login:
        hostname: "{{ grid_endpoint }}"
        username: "{{ grid_username }}"
        password: "{{ grid_password }}"
        validate_certs: false
      register: login 

        #    - name: Get StorageGRID auth token
        #na_sg_grid_login:
        #sg_api_url: "{{ grid_endpoint }}"
        #username: "{{ grid_username }}"
        #password: "{{ grid_password }}"
        #validate_certs: "{{ validate_certs }}"
        #register: login

    - name: Create/ensure S3 HTTPS load balancer endpoint
      netapp.storagegrid.na_sg_grid_gateway:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ login.na_sa_token }}"
        validate_certs: "{{ validate_certs }}"
        state: present

        display_name: "{{ lb_display_name }}"
        port: "{{ lb_port }}"
        secure: "{{ lb_secure }}"
        default_service_type: "{{ lb_default_service_type }}"

        # global binding (default) – listens on all eligible nodes
        binding_mode: global

        # comment these three lines out to use default certificates
        #server_certificate: "{{ lb_server_certificate }}"
        #private_key: "{{ lb_private_key }}"
        #ca_bundle: "{{ lb_ca_bundle | default(omit) }}"
      register: lb_endpoint

    - debug:
        var: lb_endpoint.resp

