---
- name: Delete StorageGRID Bucket
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.storagegrid

  vars_files:
    - global_vars.yml

  vars_prompt:
    - name: tenant_id
      prompt: "enter tenant id"
      default: "default"
      private: false

    - name: user_name
      prompt: "enter tenant root user name"
      default: "root"
      private: false

    - name: user_pass
      prompt: "enter tenant root user password"
      default: "br@@mspun111"
      private: true

    - name: bucket_name
      prompt: "enter bucket name to DELETE"
      default: "default"
      private: false

  tasks:
    - name: Get Grid Authorization Token
      uri:
        url: "https://192.168.4.230:443/api/v3/authorize"
        method: POST
        body: >
          {"accountId": "{{ tenant_id }}",
           "username": "{{ user_name }}",
           "password": "{{ user_pass }}"}
        body_format: json
        validate_certs: false
        status_code: [200]
      register: auth

    - name: Delete S3 Bucket
      netapp.storagegrid.na_sg_org_container:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ auth.json.data }}"
        validate_certs: false
        state: absent
        name: "{{ bucket_name }}"
