# this playbook will list all tenants' data
---
- name: List StorageGRID tenants
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - global_vars.yml

  tasks:
    - name: Get bearer token from StorageGRID
      uri:
        url: "{{ grid_endpoint }}/api/v4/authorize"
        method: POST
        body_format: json
        body:
          username: "{{ grid_username }}"
          password: "{{ grid_password }}"
        status_code: 200
        validate_certs: false
      register: auth

    - name: Set bearer token fact
      set_fact:
        bearer_token: "{{ auth.json.data }}"
      when: auth.json.data is defined

    - name: Get list of tenants from StorageGRID
      uri:
        url: "{{ grid_endpoint }}/api/v4/grid/accounts"
        method: GET
        headers:
          Authorization: "Bearer {{ bearer_token }}"
          Accept: "application/json"
        validate_certs: false
      register: tenant_response

    - name: list tenants
      debug:
        msg: "id={{ item.id }}, name={{ item.name }}"
      loop: "{{ tenant_response.json.data }}"
      loop_control:
        label: "{{ item.name }}"
