---
# start of play
- name: Create StorageGRID load balancer endpoint
  hosts: localhost
  connection: local
  gather_facts: false
# use storagegrid collection
  collections:
    - netapp.storagegrid

# use global_variables file
  vars_files:
    - global_vars.yml

# prompt user for load balancer endpoint parameters
  vars_prompt:
    - name: lb_display_name 
      prompt: "display name"
      default: "------"
      private: "no"
    - name: lb_port 
      prompt: "port"
      default: "------"
      private: "no"
    - name: lb_secure
      prompt: "HTTPS"
      default: "false" #boolean "true/false"
      private: "no"
    - name: lb_default_service_type
      prompt: "default service type"
      default: s3
      private: no
    - name: state 
      prompt: "present or absent (absent needs name and port)"
      default: present
      private: no
 
  tasks:

# get auth token, we are not using a role
    - name: Get StorageGRID auth token
      netapp.storagegrid.na_sg_grid_login:
        hostname: "{{ grid_endpoint }}"
        username: "{{ grid_username }}"
        password: "{{ grid_password }}"
        validate_certs: false
# this will store what the na_sg_grid_login module returns in the variable login
      register: login 


    - name: Create/ensure S3 HTTPS load balancer endpoint
      netapp.storagegrid.na_sg_grid_gateway:
        api_url: "{{ grid_endpoint }}"

# “pass the authentication token from the login task (login.na_sa_token) 
# to the module’s auth_token parameter.”
        auth_token: "{{ login.na_sa_token }}"
        validate_certs: "{{ validate_certs }}"
# state is present or absent
        state: "{{ state }}" 

        display_name: "{{ lb_display_name }}"
        port: "{{ lb_port }}"
        secure: "{{ lb_secure }}"
        default_service_type: "{{ lb_default_service_type }}"

# global binding (default) – listens on all eligible nodes
        binding_mode: global

# store all the return values in the variable lb_endpoint
      register: lb_endpoint

# show API response for debugging.
    - debug:
        var: lb_endpoint.resp
