---
- name: Delete Gateway Endpoint by name/port
  hosts: localhost
  gather_facts: false

  vars_files:
    - global_vars.yml

  vars_prompt:
    - name: id 
      prompt: id 
      private: no
    - name: port
      prompt: port
      private: no

  roles:
    - grid_auth

  tasks:
    - name: Delete gateway endpoint by name and port 
      netapp.storagegrid.na_sg_grid_gateway:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ bearer_token }}"
        gateway_id: "{{ id }}"
        port: "{{ port }}"
        state: absent
        validate_certs: false

