####################
# This play uses a random number if the default
# value for the bucketname is not modified is unchanged
###################
---
- name: Create StorageGRID Bucket
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - netapp.storagegrid

  vars_files:
    - global_vars.yml

  vars_prompt:
    - name: tenant_id
      prompt: "enter tenant id"
      default: "18815655567777745228"
      private: false

    - name: user_name
      prompt: "enter tenant root user name"
      default: "root"
      private: false

    - name: user_pass
      prompt: "enter tenant root user password "
      default: "Netapp1!"
      private: true

    - name: bucket_name
      prompt: "enter bucket name"
      default: "default"
      private: false

  tasks:
    - name: Generate random suffix
      set_fact:
        my_random: "{{ 100000 | random }}"
      run_once: true

    - name: Generate random suffix only if user kept default
      ansible.builtin.set_fact:
        bucket_name: "{{ bucket_name }}-{{ my_random }}"
      when: bucket_name == 'default'


    - name: Get tenant auth token via sg_login
      netapp.storagegrid.na_sg_grid_login:
        hostname: "https://192.168.0.80"
        username: "{{ user_name }}"
        password: "{{ user_pass }}"
        tenant_id: "{{ tenant_id }}"
        validate_certs: false
      register: auth

    # - name: Show login result
    # debug:
    # var: auth

    - name: Create S3 Bucket
      netapp.storagegrid.na_sg_org_container:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ auth.na_sa_token }}"
        validate_certs: false
        state: present
        name: "{{ bucket_name }}"
        region: us-east-1
