#this playbook has two plays
#the first play lists the tenants
#the second play creates the bucket
---

#first play
- name: List StorageGRID tenants
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - netapp.storagegrid
#rest of first play
#inspect m4_4_list_short.yml  

#start of second play
- name: Create StorageGRID Bucket
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - netapp.storagegrid
#rest of second play
#inspect m5_1_create_bucket_module.yml


