---
- name: List StorageGRID tenant buckets via Tenant API
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    grid_endpoint: "https://192.168.0.80"   # tenant/admin endpoint
    validate_certs: false

  vars_prompt:
    - name: tenant_id
      prompt: "Tenant ID"
      default: "18815655567777745228"
      private: no
    - name: tenant_root_user
      prompt: "Tenant username"
      private: no
      default: "root"
    - name: tenant_root_pass
      prompt: "Tenant password"
      default: "Netapp1!"
      private: yes

  roles:
    - tenant_auth

  tasks:

    - name: List buckets (containers)
      uri:
        url: "{{ grid_endpoint }}/api/v3/org/containers"
        method: GET
        headers:
          Authorization: "Bearer {{ bearer_token }}"
          Accept: "application/json"
        validate_certs: "{{ validate_certs }}"
        status_code: [200]
      register: containers

    - name: Show bucket names only
      debug:
        msg: "Bucket: {{ item.name }}"
      loop: "{{ containers.json.data }}"
      loop_control:
        label: "{{ item.name }}"
