---
- name: Delete StorageGRID Bucket
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - netapp.storagegrid
  vars_files:
    - global_vars.yml
  roles:
    - tenant_auth
  vars_prompt:
    - name: tenant_id
      prompt: "enter tenant id"
      default: "18815655567777745228"
      private: false

    - name: tenant_username
      prompt: "enter user name"
      default: "root"
      private: false

    - name: tenant_password
      prompt: "enter password "
      default: "br@@Mspun111"
      private: true

    - name: bucket_name
      prompt: "enter bucket name"
      default: "default"
      private: false
  tasks:
    - name: Delete S3 Bucket
      netapp.storagegrid.na_sg_org_bucket:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ auth.json.data }}"
        validate_certs: false
        state: absent
        name: "{{ bucket_name }}"
