---
- name: Create StorageGRID tenant user
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - global_vars.yml
  vars_prompt:
    - name: new_user_name
      prompt: "username to create"
      default: "user1"
      private: "no"
    - name: tenant_id
      prompt: "account_id"
      default: "06720005734697258898"
      private: false
    - name: tenant_username
      prompt: "tenant admin"
      default: "root"
      private: false
    - name: tenant_password
      prompt: "tenant_password"
      default: "br@@mspun111"
      private: true

  roles:
    - tenant_auth
  tasks:
    - name: Create tenant local user
      ansible.builtin.uri:
        url: "{{ grid_endpoint }}/api/v3/org/users"
        method: POST
        body_format: json
        body:
          fullName: "{{ new_user_name }}"
          uniqueName: "user/{{ new_user_name }}"
        headers:
          Authorization: "Bearer {{ bearer_token}}"
          Content-Type: "application/json"
        validate_certs: false
        status_code: 201
      register: uniqueName

    - name: Show result
      ansible.builtin.debug:
        var: uniqueName.json
