---
- name: Delete StorageGRID tenant user
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - netapp.storagegrid

  vars:
    grid_endpoint: "https://192.168.4.230:443"

  vars_prompt:
    - name: tenant_id
      prompt: "Enter tenant ID"
      private: false

    - name: tenant_admin_user
      prompt: "Enter tenant admin username"
      default: root
      private: false
      default: "root"

    - name: tenant_admin_user_password
      prompt: "Enter tenant admin password"
      default: br@@mspun111
      private: true

    - name: user_simple_name
      prompt: "Enter tenant user name to DELETE (simple, e.g. wilma)"
      private: false

  roles:
    - tenant_auth

  tasks:

    - name: Delete tenant user
      netapp.storagegrid.na_sg_org_user:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ bearer_token }}"
        validate_certs: false
        state: absent
        unique_name: "user/{{ user_simple_name }}"
      register: deleted_user

    - name: Show delete result
      debug:
        var: deleted_user
