---
- name: list tenants 
  connection: local
  hosts: localhost
  gather_facts: false

  collections:
    - netapp.storagegrid

  vars_files:
    - global_vars.yml

  roles:
    - grid_auth
    - list_tenants


- name: Change StorageGRID tenant root password
  connection: local
  hosts: localhost
  gather_facts: false

  collections:
    - netapp.storagegrid

  vars_files:
    - global_vars.yml

  roles:
    - grid_auth

  vars_prompt:
    - name: tenant_id
      prompt: Enter the Tenant ID from the list above
      private: no
    - name: tenant_name
      prompt: Tenant name
      default: "------"
      private: no
    - name: tenant_pass
      prompt: Tenant password
      private: yes

  tasks:
    - name: Change tenant root password
      na_sg_grid_account:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ bearer_token }}"
        validate_certs: false
        account_id: "{{ tenant_id }}"
        name: "{{ tenant_name }}"
        password: "{{ tenant_pass }}"
        update_password: always
        state: present
        allow_platform_services: false
        use_own_identity_source: false
        protocol: s3
      no_log: true  # hides password in logs

