---
- name: List ILM pools, rules and policies
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.storagegrid

  vars:
    grid_endpoint: "https://192.168.4.230"
    grid_username: "root"
    grid_password: "br@@mspun111"

  roles:
    - grid_auth

  tasks:
    - name: Get ILM pools (list)
      na_sg_grid_ilm_pool:
        api_url: "{{ grid_endpoint }}"
        username: "{{ grid_username }}"
        password: "{{ grid_password }}"
        auth_token: "{{ bearer_token }}"
        validate_certs: false
        # name omitted on purpose so module returns all pools, not just one
        state: present
      register: ilm_pools

    - name: Show ILM pools
      debug:
        var: ilm_pools.resp

    - name: Get ILM rules (list)
      na_sg_grid_ilm_rule:
        api_url: "{{ grid_endpoint }}"
        username: "{{ grid_username }}"
        password: "{{ grid_password }}"
        validate_certs: false
        state: present
      register: ilm_rules

    - name: Show ILM rules
      debug:
        var: ilm_rules.resp

    - name: Get ILM policies (list)
      na_sg_grid_ilm_policy:
        api_url: "{{ grid_endpoint }}"
        username: "{{ grid_username }}"
        password: "{{ grid_password }}"
        auth_token: "{{ bearer_token }}"
        validate_certs: false
        state: present
      register: ilm_policies

    - name: Show ILM policies
      debug:
        var: ilm_policies.resp

