---
- name: Manage ILM policy tag
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.storagegrid

  vars_files:
    - vars.yml

  tasks:
    - name: Create ILM policy tag "finance-tag"
      na_sg_grid_ilm_policy_tag:
        api_url: "{{ grid_endpoint }}"
        username: "{{ grid_username }}"
        password: "{{ grid_password }}"
        validate_certs: false
        state: present
        name: "finance-tag"
        description: "Finance buckets ILM"
        policy_id: "f9cecfd8-fe93-4529-b883-d1707e753009"   # ILM policy ID

