# roles/tenant_user_pass/tasks/main.yml
- name: Change tenant root password
  netapp.storagegrid.na_sg_grid_account:
    api_url: "{{ grid_endpoint }}"
    auth_token: "{{ bearer_token }}"
    validate_certs: false
    account_id: "{{ tenant_id }}"
    name: "{{ tenant_name }}"
    password: "{{ tenant_pass }}"
    update_password: "always"
    state: "present"
    allow_platform_services: false
    use_own_identity_source: false
    protocol: s3
  no_log: false
