- name: generate auth token for org module on StorageGRID
  netapp.storagegrid.na_sg_grid_login:
    hostname: "{{ grid_endpoint }}"
    username: "{{ tenant_root_user }}"
    password: "{{ tenant_root_pass }}"
    tenant_id: "{{ tenant_id }}"
    validate_certs: false
  register: auth

- name: Expose token as bearer_token
  set_fact:
    bearer_token: "{{ auth.na_sa_token }}"
