---
- name: Get Grid Admin Auth Token
  connection: local
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.storagegrid

  vars:
    myvar: peter

  vars_prompt:
    - name: grid_endpoint
      prompt: endpoint
      default: 192.168.0.80:443
      private: false
    - name: grid_username
      prompt: username
      default: root 
      private: false
    - name: grid_password
      prompt: password
      default: Netapp1! 
      private: true
  tasks:
    - name: Show result
      ansible.builtin.debug:
        msg: 
          grid_endpoint: "{{ grid_endpoint }}"
          grid_user: "{{ grid_username }}"
          grid_pass: "{{ grid_password }}"
          my_name: "{{ myvar }}"
