---
# this playbook uses modules form the netapp.storagegrid collection
- name: Get Grid Admin Auth Token
  connection: local
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.storagegrid
  # define endpoint, user and pass
  vars:
    grid_endpoint: "https://192.168.0.80:443"
    grid_username: "root"
    grid_password: "Netapp1!"
      
  # connect to endpoint and use the na_sg_grid_login module
  tasks:
    - name: Get Grid Authorization Token
      netapp.storagegrid.na_sg_grid_login:
        hostname: "{{ grid_endpoint }}"
        username: "{{ grid_username }}"
        password: "{{ grid_password }}"
        validate_certs: false
      register: auth

    # how to find out what the parameter it is you need instead of
    # json.auth.data when using na_sg_grid_login instead of the uri method?
    # ----------------------------------------
    # - name: show full variable
    #  ansible.builtin.debug:
    #    var: auth
    # this will tell you to use na_sa_token.
    # the module uses "na_sa_token" as the data field that contains the token
    # -----------------------------------------
    # - name: Display Auth using msg
    #   ansible.builtin.debug:
    #     msg: "Token: {{ auth.na_sa_token }}"
    # -----------------------------------------   
    # Instead using msg: you can also create a variable you could use
    # further in the playbook
    - name: set fact. 
      set_fact:
        bearer_token: "{{ auth.na_sa_token }}"
    - name: Display Auth using msg
      ansible.builtin.debug:
        msg: "Token: {{ bearer_token }}"
