---
- name: Create StorageGRID tenant
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - myvars.yml

  roles:
    - grid_token

  tasks:
    - name: create a tenant account
      netapp.storagegrid.na_sg_grid_account:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ bearer_token }}"
        validate_certs: false
        state: present
        name: "{{ tenant_name }}"
        protocol: s3
        management: true
        use_own_identity_source: false
        allow_platform_services: false
        password: "{{ tenant_password }}"
        quota_size: 0
