---
- name: Create StorageGRID tenant
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - myvars.yml

  vars_prompt:
    - name: tenant_password 
      prompt: "Tenant root password"
      private: true

  roles:
    - grid_token

  tasks:
    - name: Set grid token
      ansible.builtin.set_fact:
        grid_token: "{{ auth.na_sa_token }}"

    - name: create a tenant account
      netapp.storagegrid.na_sg_grid_account:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ grid_token }}"
        validate_certs: false
        state: present 
        name: "{{ tenant_name }}" 
        protocol: s3
        management: true
        use_own_identity_source: false
        allow_platform_services: false
        password: "{{ tenant_password }}"
        quota_size: 0
          # no_log: true
