---
- name: List StorageGRID tenants
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - global_vars.yml

  roles:
    - grid_auth

  tasks:
    - name: List all tenant accounts
      netapp.storagegrid.na_sg_grid_info:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ bearer_token }}"
        validate_certs: false
        gather_subset:
          - grid_accounts_info
      register: sg_info
      no_log: true

    - name: Create tenant name-to-ID mapping 
      set_fact:
        tenant_map: "{{ dict(sg_info.sg_info['grid/accounts'].data | 
     map(attribute='name') | zip(sg_info.sg_info['grid/accounts'].data | 
     map(attribute='id'))) }}"

    - name: Show mapping
      debug:
        var: tenant_map
