# this playbook will list all tenants' data
---
- name: List StorageGRID tenants
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - global_vars.yml

  roles:
    - grid_token

  tasks:
    - name: List all tenant accounts
      netapp.storagegrid.na_sg_grid_info:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ bearer_token }}"
        validate_certs: false
        gather_subset:
          - grid_accounts_info
      register: sg_grid_info
      no_log: false

    - name: show accounts
      debug:
        var: sg_grid_info
