---
- name: List StorageGRID tenants
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - netapp.storagegrid

  vars_files:
    - global_vars.yml

  vars_prompt:
    - name: grid_user
      prompt: "enter GRID admin user"
      default: "root"
      private: false

    - name: grid_pass
      prompt: "enter GRID admin password"
      default: "Netapp1!"
      private: true

  roles:
    - grid_token
  tasks:
    - name: List tenants (accounts)
      netapp.storagegrid.na_sg_grid_info:
        api_url: "https://192.168.0.80"
        auth_token: "{{ bearer_token }}"
        validate_certs: false
        gather_subset:
          - grid_accounts_info
      register: data 

    - name: Show tenant IDs and names
      debug:
        msg: "id={{ item.id }}, name={{ item.name }}"
      loop: "{{ data.sg_info['grid/accounts'].data }}"
      loop_control:
        label: "{{ item.name }}"

- name: Create StorageGRID Bucket
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - netapp.storagegrid

  vars_files:
    - global_vars.yml

  vars_prompt:
    - name: tenant_id
      prompt: "enter tenant id"
      default: "18815655567777745228"
      private: false

    - name: tenant_user_name
      prompt: "enter tenant root user name"
      default: "root"
      private: false

    - name: tenant_user_pass
      prompt: "enter tenant root user password "
      default: "Netapp1!"
      private: true

    - name: bucket_name
      prompt: "enter bucket name"
      default: "default"
      private: false

  roles:
    - tenant_token

  tasks:
    - name: Generate random suffix
      set_fact:
        my_random: "{{ 100000 | random }}"
      run_once: true

    - name: Generate random suffix only if user kept default
      ansible.builtin.set_fact:
        bucket_name: "{{ bucket_name }}-{{ my_random }}"
      when: bucket_name == 'default'

    - name: Create S3 Bucket
      netapp.storagegrid.na_sg_org_container:
        api_url: "{{ grid_endpoint }}"
        auth_token: "{{ bearer_token }}"
        validate_certs: false
        state: present
        name: "{{ bucket_name }}"
        region: us-east-1
