---
- name: Delete StorageGRID tenant
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: grid_addr
      prompt: "Grid admin address"
      default: "192.168.4.230"
      private: no

    - name: grid_user
      prompt: "Grid admin username"
      default: "root"
      private: no

    - name: grid_pass
      prompt: "Grid admin password"
      default: "br@@mspun111"
      private: yes

    - name: tenant_id
      prompt: "Tenant ID to delete"
      private: no

  tasks:
    - name: Set grid token
      netapp.storagegrid.na_sg_grid_login:
        hostname : "{{ grid_addr }}"          # base URL, no /api/v3/authorize
        username: "{{ grid_user }}"
        password: "{{ grid_pass }}"
        validate_certs: true
        ca_path: "./m2_sgrid_admin.pem"
      register: auth

      ansible.builtin.debug:
        msg: "Grid Admin Auth Token: {{ auth.auth_token }}"
      ansible.builtin.set_fact:
        grid_token: "{{ auth.json.data }}"

#    - name: Delete tenant account
##
#      register: delete_result
#
#    - name: Show delete result
#      ansible.builtin.debug:
#        var: delete_result.status
