---
- name: Get Grid Admin Auth Token
  connection: local
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.storagegrid

  vars_prompt:
    - name: grid_endpoint
      prompt: endpoint
      default: 192.168.4.230:443
      private: false
    - name: grid_user 
      prompt: username
      default: root 
      private: false
    - name: grid_pass 
      prompt: password
      default: ------ 
      private: true

  tasks:
    - name: Show result
      ansible.builtin.debug:
        msg: 
          grid_endpoint: "{{ grid_endpoint }}"
          grid_user: "{{ grid_user }}"
          grid_pass: "{{ grid_pass }}"
